In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt # a specialized 2d plotting library to visualise Numpy computations
import statsmodels.api as sm
    #these where imported after we set up the regression line
import seaborn as sns # a similar package to matplotlib but it's more advanced at it
sns.set() # basically it's like the relationship between css and html XD
sns.set_theme(style="whitegrid")

#these are the ones we are gonna mainly use for now

# import scipy # ecosystem for some of these libraries
# import sklearn # machine learning librarie it's gonna help later on

In [31]:
data = pd.read_csv('Automobile_data.csv') # this is used to import the data
data['horsepower'] = data['horsepower'].replace('?', np.nan)
data['price'] = data['price'].replace('?',np.nan)
data['horsepower'] = data['horsepower'].astype(float)
data['price'] = data['price'].astype(float)


In [32]:
data_og = data[['highway-mpg' , 'engine-size' , 'horsepower' , 'price']].dropna()
data_ogf = data[['highway-mpg', 'horsepower', 'price' ]].dropna()


In [33]:
data3 = data[['highway-mpg' , 'engine-size' , 'horsepower' , 'curb-weight']].dropna()

In [34]:
data2 = data3[['highway-mpg' , 'horsepower' ]]

In [35]:
print(data3['highway-mpg'].dropna().count())
print(data3['curb-weight'].dropna().count())
print(data3['horsepower'].dropna().count())
print(data3['engine-size'].dropna().count())
print(data[['price']].dropna())

203
203
203
203
       price
0    13495.0
1    16500.0
2    16500.0
3    13950.0
4    17450.0
..       ...
200  16845.0
201  19045.0
202  21485.0
203  22470.0
204  22625.0

[201 rows x 1 columns]


In [42]:


# drop the rows using the drop() method
X = data2.head(int(203 * 0.8)) # this drops the 20% of the data and leaves 80%
y = data[['price']].dropna()
from sklearn.model_selection import train_test_split
y = y.head(int(len(data2) * 0.8))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# the regression 
from sklearn import linear_model
regr = linear_model.LinearRegression().fit(X_train, y_train) #all the magic happens here in this method



In [43]:
regr.coef_

array([[-491.04757265,  -10.08843618]])

In [44]:
regr.score(X,y)

0.055334066425552386

In [45]:
predictor = regr.predict(X_test)

In [46]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, predictor)
r2 = r2_score(y_test, predictor)
print('Mean Squared Error:', mse)
print('R-squared:', r2)

Mean Squared Error: 104517643.156877
R-squared: -0.2899696199409991


# idk why R-squared is so low 

## verifying the VIF for each variable

In [47]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
def calc_vif(X):

    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return(vif)

X = data_ogf
print(calc_vif(X))

     variables        VIF
0  highway-mpg   4.298398
1   horsepower  18.102383
2        price  11.202365


In [48]:
data

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0      111.0   
1            130         mpfi  3.47    2.68               9.0      111.0   
2            152         mpfi  2.68    3.47               9.0      154.0   
3            109         mpfi  3.19     3.4              10.0      102.0   
4            136         mpfi  3.19     3.4               8.0      115.0   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5      114.0   
201          141         mpfi  3.78    3.15               8.7      160.0   
202          173         mpfi  3.58    2.87               8.8      134.0   
203          145          idi  3.01     3.4              23.0      106.0   
204          141         mpfi  3.78    3.15               9.5      114.0   

     peak-rpm city-mpg highway-mpg    price  
0        5000       21          27  13495.0  
1        5000       21          27  16500.0  
2        5000       19          26  16500.0  
3        5500       24          30  13950.0  
4        5500       18          22  17450.0  
..        ...      ...         ...      ...  
200      5400       23          28  16845.0  
201      5300       19          25  19045.0  
202      5500       18          23  21485.0  
203      4800       26          27  22470.0  
204      5400       19          25  22625.0  

[205 rows x 26 columns]

In [49]:
# data['normalized-losses'] = data['normalized-losses'].replace('?', np.nan)
# data['fuel-type'] = data['fuel-type'].replace('gas', '1')
# data['fuel-type'] = data['fuel-type'].replace('diesel', '0')
# data['fuel-type'] = data['fuel-type'].astype(float)
# data['city-mpg'] = data['city-mpg'].replace('?',np.nan)
# data['normalized-losses'] = data['normalized-losses'].astype(float)
# data['city-mpg'] = data['city-mpg'].astype(float)
# data['peak-rpm'] = data['peak-rpm'].replace('?', np.nan)
# data['peak-rpm'] = data['peak-rpm'].astype(float)

In [50]:
set(data['fuel-system'])

{'1bbl', '2bbl', '4bbl', 'idi', 'mfi', 'mpfi', 'spdi', 'spfi'}

In [51]:
set(data['num-of-cylinders'])

{'eight', 'five', 'four', 'six', 'three', 'twelve', 'two'}

In [52]:
set(data['make'])

{'alfa-romero',
 'audi',
 'bmw',
 'chevrolet',
 'dodge',
 'honda',
 'isuzu',
 'jaguar',
 'mazda',
 'mercedes-benz',
 'mercury',
 'mitsubishi',
 'nissan',
 'peugot',
 'plymouth',
 'porsche',
 'renault',
 'saab',
 'subaru',
 'toyota',
 'volkswagen',
 'volvo'}

In [53]:
regr = linear_model.LinearRegression().fit(np.array(x1).reshape(162,2), y)

## retrying using OLS() because i lost faith on R-squared 눈_눈

In [54]:
x1 = data2[['highway-mpg','horsepower']].dropna().head(int(203*0.8))
x = np.array(sm.add_constant(x1)).reshape(int(x1.size/2),3) # constant x
y = data['price'].dropna().head(162)
result = sm.OLS(y,x).fit() #fit() helps visualising the OLS line in the best way/ position possible
# (the purple line down there)
result.summary() # this gives various info to us about the regession

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.072
Model:                            OLS   Adj. R-squared:                  0.060
Method:                 Least Squares   F-statistic:                     6.142
Date:                Fri, 21 Apr 2023   Prob (F-statistic):            0.00269
Time:                        20:50:32   Log-Likelihood:                -1691.1
No. Observations:                 162   AIC:                             3388.
Df Residuals:                     159   BIC:                             3398.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        2.29e+04   6420.889      3.566      0.000    1.02e+04    3.56e+04
x1          -315.8394    139.223     -2.269      0.025    -590.805     -40.874
x2             0.8119     24.019      0.034      0.973     -46.626      48.250
==============================================================================
Omnibus:                       53.463   Durbin-Watson:                   0.623
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              102.058
Skew:                           1.577   Prob(JB):                     6.89e-23
Kurtosis:                       5.274   Cond. No.                     1.12e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.12e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## this is just to show coefficients and R-squared which is low  e(ço_yè"ç_"t'ygheiue

In [55]:
regr.coef_

array([[-315.83938942,    0.81195   ]])

In [58]:
regr.predict(data2[['highway-mpg','horsepower']].tail(203-162))

C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([[12215.51628516],
       [13828.81513221],
       [13828.81513221],
       [13516.22354279],
       [13516.22354279],
       [13516.22354279],
       [13516.22354279],
       [13516.22354279],
       [13516.22354279],
       [12233.37918514],
       [12533.79152458],
       [12865.05796398],
       [12865.05796398],
       [12865.05796398],
       [15447.79762925],
       [15447.79762925],
       [15443.73787926],
       [15443.73787926],
       [ 8410.82851216],
       [12227.69553515],
       [ 8410.82851216],
       [12227.69553515],
       [12227.69553515],
       [ 9687.17726982],
       [12871.55356397],
       [13810.95223224],
       [13810.95223224],
       [15406.38817931],
       [10950.53482749],
       [13177.6495534 ],
       [14146.27842163],
       [14146.27842163],
       [14146.27842163],
       [14146.27842163],
       [16080.28835809],
       [16080.28835809],
       [14146.27842163],
       [15131.14628983],
       [15741.7143687 ],
       [14455.62221105],
